### PR TITLE
Update mobiles.yml

### PR DESCRIPTION
**Pull request by AtomCZ**
updated and added new devices

### CODE REVIEW

**Comment by AtomCZ** [comment]
Why it failed?

**Comment by sanchezzzhak** [comment]
Changes to regular expressions fail the tests
View tests result https://travis-ci.org/matomo-org/device-detector/jobs/559427819
Local tests run 
`php ./vendor/phpunit/phpunit/phpunit`

**Comment by mimmi20** [comment]
@AtomCZ You forgot to add test cases for the new deveices.

**Comment by AtomCZ** [comment]
@mimmi20 oh, how can i do this? :-O

**Comment by mimmi20** [comment]
@sanchezzzhak Could you tell?

**Comment by sanchezzzhak** [comment]
The easiest way to create a test fixture 
using the file (misc/test.php) in the mics folder
`cd project dir`
`cd misc`
`php test.php "Mozilla/5.0 (Linux; Android 4.2.2; QMV7B Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36"`
copy test result
```
-
  user_agent: Mozilla/5.0 (Linux; Android 4.2.2; QMV7B Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36
  os:
    name: Android
    short_name: AND
    version: 4.2.2
    platform: ""
  client:
    type: browser
    name: Chrome
    short_name: CH
    version: 39.0.2171.93
    engine: Blink
    engine_version: ""
  device:
    type: tablet
    brand: V4
    model: Ellipsis 7
  os_family: Android
  browser_family: Chrome
```
paste text to file `/srv/www/my-project/device-detector/Tests/fixtures/smartphone-10.yml`

It is important that your result is correct in the test areas, in cases of device detection
(I myself use this method to create fixtures, check only: type,model, brand)
```
    type: <here>
    brand <here>
    model: <here>
```
Run test console `php ./vendor/phpunit/phpunit/phpunit`


It is better to use IDE, so it's easier to see the tests (PhpStorm)
Screen configuration 
Screenshot_20190717_095537

Screen run tests (shit+f10)
Screenshot_20190717_135237

**Comment by sgiehl** [comment]
closing as most of it should be included in #6000.

**Pull request closed without merging**
