### PR TITLE
Added a few Android devices and variants

### PR DESCRIPTION
**Pull request by GregOriol**
Mistakenly closed the previous PR #6060 by deleting the branch too soon, sorry!

### CODE REVIEW

**Comment by GregOriol** [comment]
(tests are failing only on an older version of php and for a reason not related to the changes)

**Comment by mimmi20** [comment]
@GregOriol Can you restart that build?

**Comment by GregOriol** [comment]
@mimmi20 I don't think we should spend even a tiny bit of time handling this kind of fail: it's not related to the PR at all...

**Comment by sgiehl** [comment]
@GregOriol  would you mind solving the conflicts?

**Comment by GregOriol** [comment]
@sgiehl Done!

**Comment by sgiehl** [comment]
thx

**Pull request merged**
