### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by Johnbad2000**
### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [x] Existing documentation updated if needed

### CODE REVIEW

**Comment by Johnbad2000** [comment]
Good

**Comment by Simbiat** [comment]
Why though?

**Comment by Johnbad2000** [comment]
I feel I am being watched

**Comment by Simbiat** [comment]
You are, because your account seems suspicious, but that does not answer my question. What's the benefit of this PR for the project?

**Comment by Johnbad2000** [comment]
I just want to stop all I am experiencing,please sir I don't really know much about it but I really feel it will help my phone behave normal,you can block me but help me repair my phone

**Comment by Simbiat** [comment]
Ok, you are a bot, clearly. Account reported

**Comment by Johnbad2000** [comment]
I am no bot

**Comment by Simbiat** [comment]
If you were not a bot, you would have been able to answer my question

**Comment by Johnbad2000** [comment]
>

**Pull request closed without merging**
