### PR TITLE
Update smartphone-11.yml

### PR DESCRIPTION
**Pull request by AtomCZ**
new devices Lenovo, Samsung

### CODE REVIEW

**Comment by AtomCZ** [comment]
Why is this happening?

**Comment by sanchezzzhak** [comment]
Use one branch for correction. Just send new commits. No need to create a new PR.

**Comment by AtomCZ** [comment]
@sanchezzzhak cant see any buttons for new commit here on github :(

**Comment by sgiehl** [comment]
merged the changes together with #5997 into #6000

**Pull request closed without merging**
