### PR TITLE
Detect browser OceanHero

### PR DESCRIPTION
**Pull request by sanchezzzhak**

### CODE REVIEW

**Comment by sgiehl** [comment]
That seems to be a chrome extension only. See https://chrome.google.com/webstore/detail/oceanhero-save-the-oceans/cdbccfkcpkmimlajcjpodelocoeifjhp
Or is there a custom chromium version available somewhere as well?

**Comment by sanchezzzhak** [comment]
for mobile  devices, an application:
https://play.google.com/store/apps/details?id=com.oceanhero.search

**Comment by sgiehl** [comment]
I see. I've just installed that app and it actually uses this UA:
```
Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.91 Mobile OceanHero/6 Safari/537.36
```
So guess the other one is for the extension only

**Comment by sanchezzzhak** [comment]
I installed the extension on my computer useragent outputs - standard chrome
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

I can make a stricter rule
`Android.+OceanHero/([\.\d]+)` 
do it?

**Comment by sgiehl** [comment]
Seems there is also a MacOS App: https://apps.apple.com/us/app/oceanhero/id1503330056?mt=12
Can't test it, but guess it's fine to keep it the way it is.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
