### PR TITLE
Added Mobiistar Android smartphones

### PR DESCRIPTION
**Pull request by GregOriol**

### CODE REVIEW

**Comment by GregOriol** [comment]
I don't know how you choose brand codes, I added it as "M6" because most others were already used (MI/MB/MS/...). Let me know if you think some other code would be better!

**Comment by sgiehl** [comment]
The code is fine. Thanks for the PR

**Comment by Findus23** [comment]
@GregOriol Do you have any idea for an square icon?



This can't really be cropped in a proper way.

**Comment by GregOriol** [comment]
@Findus23 maybe use the double "i" with stars?

**Comment by Findus23** [comment]
@GregOriol 
Thanks for the idea. Thankfully the image was large enough that I could crop it.

https://github.com/matomo-org/matomo-icons/commit/c37c3dfd643d4202897d3bf47d469251e4062eba

**Pull request merged**
