### PR TITLE
Detect apps: Pandora, NPR One, Wirtschafts Woche, Microsoft Outlook, TVirl, ChMate, 2tch, Ciisaa, BB2C, twinkle, JaneStyle, JaneView, BathyScaphe, Live5ch

### PR DESCRIPTION
**Pull request by sanchezzzhak**

### CODE REVIEW

**Comment by sanchezzzhak** [comment]
I do not know which category of applications to include these applications:

Browser Name: Live5ch
User-Agent: Monazilla/1.00 Live5ch/1.52 Windows/10.0.17134

 Browser Name: BathyScaphe
User-Agent: Monazilla/1.00 BathyScaphe/1057 Mac OS X/10.11.6
Link: https://osdn.net/projects/bathyscaphe/

 Browser Name: JaneView
User-Agent: Monazilla/1.00 (JaneView/1501150412)

**Review by sgiehl — DISMISSED** [review]

**Comment by sgiehl** [comment]
@sanchezzzhak  regarding the other browser. I'm not sure what type they are either. Did a quick search on the web, but didn't find anything useful. Don't think they are very common. So might be fine to leave them away for now maybe.

**Comment by sanchezzzhak** [comment]
this is a message board / bulletin board similar to a forum.
can I set the `PIM` type?

**Comment by sgiehl** [comment]
Sure, if that fits most, feel free to use it.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
