### PR TITLE
Adds detection for 25 new browsers and improves some detection for existent browsers

### PR DESCRIPTION
**Pull request by liviuconcioiu**

### CODE REVIEW

**Comment by liviuconcioiu** [comment]
Does anyone know why it throws that last error? Also, I noticed that this file is missing `/Tests/fixtures/browser.yml`, referenced on `/Tests/Parser/Client/BrowserTest.php` line 32. Not relevant, but was above the code that tests the browsers, and got into my eyes.

**Comment by sgiehl** [comment]
@liviuconcioiu  would you mind keeping your PRs a bit smaller? It's very hard to review such big PRs and check if everything is fine. If you would create separate PRs for each browser, I could quickly review an merge each. Reviewing this one would take me a few hours, which I don't have right now :man_shrugging:

**Comment by liviuconcioiu** [comment]
Should I close it and make individual PRs?

**Comment by sgiehl** [comment]
If you have time to do so, that would help me. If the PRs are small, I will try to review them asap

**Pull request closed without merging**
