### PR TITLE
Remove unused param

### PR DESCRIPTION
**Pull request by emirb**

### CODE REVIEW

**Comment by sgiehl** [comment]
That "unused" parameter is to be consistent with doctrine/cache (https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/Cache.php#L79)

**Comment by emirb** [comment]
What's the purpose then, if Doctrine's `Cache` interface isn't implemented in `DeviceDetector\Cache\StaticCache`?

**Comment by ThaDafinser** [comment]
@emirb so Doctrine\Cache is a optional dependency and is not required, but can be used.

See here https://github.com/piwik/device-detector/blob/master/DeviceDetector.php#L747-L751

**Comment by emirb** [comment]
@ThaDafinser Thanks for clarifying. I agree it's not a clean solution, just my 5 cents.

**Comment by sgiehl** [comment]
If someone has the time to make a cleaner solution. Feel free to issue a PR for that.

**Pull request closed without merging**
