### PR TITLE
feat(stream-softwares) add support of stream softwares browser

### LINKED ISSUE #7391: detecting streaming softwares
Hello, I try to start a PR, but I think I miss something ... 

So, I open this issue . 

I'm interessted about adding streaming softwares to user agent detection 

All the UA are coming from a win 10 computer X64

---

### Xsplit Broadcaster

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 XSplitBroadcaster/4.4.2304.1201 Safari/537.36`

### PR DESCRIPTION
**Pull request by thib3113**
### Description:

Fix #7391 

It allow to detect browser included in streaming softwares . 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by sanchezzzhak — CHANGES_REQUESTED** [review]
You can't declare client type it as browser.
The type of "mobile app" client should be specified.
Don't be confused by the prefix "mobile", we plan to abandon this in the future.

**Comment by thib3113** [comment]
@sanchezzzhak In fact, I'm not sure to understand why ?

I tried to write it like a mobile app, but so I loose the engine informations (information which is maybe more important than the software version)

**Comment by sanchezzzhak** [comment]
We did not plan to introduce the type of engine for apps, this issue was also raised earlier, then and now it is pointless. #6177, #5923

Browsers must have an engine.
These applications for PR  are not browsers, although they are written in electron with HTML code output to the screen.

Applications such as the Curse client (twitch client), MangoBooster, Battle.Net launcher, Wargaming launcher, Epic Games, Steam, Origin, UplayLauncher  
They also display their content through the browser, but we don't consider them as browsers.

**Comment by liviuconcioiu** [comment]
@sanchezzzhak you should close this one too, as it has been fixed in https://github.com/matomo-org/device-detector/pull/7587

**Comment by sanchezzzhak** [comment]
resolve in #7587

**Pull request closed without merging**
