### PR TITLE
minor correction to detection of NEC devices

### PR DESCRIPTION
**Pull request by matt-kv**
It also prevents user agents containing e.g. "OfficeLiveConnector.1.3" to be wrongly detected as Nec.

### CODE REVIEW

**Comment by sgiehl** [comment]
That should not be the case. See https://github.com/piwik/device-detector/blob/master/Parser/ParserAbstract.php#L164 which is used to check the regexes. So "Connector" should not match for "NEC".

**Comment by matt-kv** [comment]
Indeed... I had only checked the regex against a list of UAs.

Anyway the major reason is to make the generic NEC regex coherent with the model specific regex. Is it a good idea or should we expect UAs beginning with "NEC" without the "-", thus matching a NEC smartphone device but no particular model ?

**Comment by sgiehl** [comment]
maybe the best would be to do something like  ```NEC[ _\-]```

**Comment by matt-kv** [comment]
no problem.

**Pull request merged**
