### PR TITLE
add FreshRSS as bot

### PR DESCRIPTION
**Pull request by Kdecherf**

### CODE REVIEW

**Comment by sgiehl** [comment]
could you also update the failing test?

**Comment by Findus23** [comment]
As SimplePie is a library and FreshRSS is an application, I think these should be changed to freshrss:

https://github.com/matomo-org/device-detector/blob/d6dbed84ac647766b69143b015f3289db91b0591/Tests/fixtures/bots.yml#L2236-L2261

**Comment by Kdecherf** [comment]
@Findus23 I will update the first test which is failing and I'll let the two others as is

**Comment by Kdecherf** [comment]
@Findus23 @sgiehl it should be good now

**Pull request merged**
