### PR TITLE
A few more Bots: DuckDuckGo Bot, "checker", Guzzle, PocketParser 

### PR DESCRIPTION
**Pull request by Findus23**
Sorry for the multiple pull requests, but I keep finding new bots.
 - DuckDuckGo Bot
 - "checker" as generic bot suffix
 - Guzzle (PHP HTTP client)
 - PocketParser (I added the new category 'Read-it-later Service')
I also wanted to add Instapaper, but they seem to use a not helpful user-agent: 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10`

### CODE REVIEW

**Comment by sgiehl** [comment]
Wouldn't be `Read-it-later Service` similar to the category `Feed Fetcher`

**Comment by Findus23** [comment]
I'm not sure. 
In my opinion they don't automatically fetch feeds, but rather crawl single articles on user action.

**Comment by Findus23** [comment]
Sorry, I didn't now that Guzzle was already added and then moved to regexes/client/libraries.yml
https://github.com/piwik/device-detector/blob/master/regexes/client/libraries.yml#L12

Should I also move the other libraries there?
https://github.com/piwik/device-detector/pull/5587/files#diff-658652a1b8930dae0035e1dee2883900R1395

Is it useful to assume that every request using the default user agent of a http library is a bot?
If yes, should the bot detection also include the regexes from regexes/client/libraries.yml?

**Comment by sgiehl** [comment]
I wouldn't assume that every HTTP library is a bot. There might be applications or apps using such HTTP libraries and shouldn't be detected as bots.

**Comment by Findus23** [comment]
I have now removed the libraries from the bot detection and added them to the libraries detection (with new tests)

**Pull request merged**
