### PR TITLE
Clean up bot regexes

### PR DESCRIPTION
**Pull request by biochimia**
### Description:

The changes in this pull request clean up regexes used to identify bots. Each change is performed in its own commit with a description of the change. Overall, the changes make the expressions stricter and more consistent, thus reducing the cognitive load for anyone perusing them.

In summary, these are the changes introduced:
- Explicitly match dots when dots are expected, essentially using `\.` where an actual dot is expected, such as in URLs;
- Harmonize version parsing to `[\d.]+`, whereas previously there were a few different ways bot versions were parsed essentially to the same effect;
- Use non-capturing regexes, where the captured string is not relevant;
- Drop wildcard matches at end of regexes, as they don't add value in identifying bots
- Prefer having `-` at end of character classes.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by mindreader** [comment]
This is a really nice pr!

**Review by sanchezzzhak — DISMISSED** [review]

**Comment by sanchezzzhak** [comment]
@biochimia pls resolve conflict for PR

**Comment by liviuconcioiu** [comment]
@sanchezzzhak can I resolve the conflicts, so we can get this PR merged?

**Comment by sanchezzzhak** [comment]
yes, (you may need the rights of a Collaborator)  
* `git fetch upstream pull/7549/head:pr_7549` 
* next fork branch `git checkout pr_7549` 
* fetch update by remote git `git fetch upstream master` 
* merge remote to into pr_7549  `git merge upstream/master` 
* resolve conflict
* git commit
* git push
done;

@sgiehl You can grant the same Collaborator rights for liviuconcioiu?

**Comment by biochimia** [comment]
Sorry for the radio silence, as I haven't been able to devote any time to this.

I don't object to @liviuconcioiu or anyone else picking up the changes and addressing the conflicts as needed—if you have the opportunity. I assume that the changes will need to be (at least partially) redone, in order to address the same issues in any new or updated regexes.

If you don't beat me to it, I will try to find some time later this week to apply the changes on a fresh pull.

**Comment by sgiehl** [comment]
> @sgiehl You can grant the same Collaborator rights for liviuconcioiu?

I'll send an invite.

**Comment by liviuconcioiu** [comment]
Thanks both for help!

**Review by sanchezzzhak — APPROVED** [review]

**Pull request merged**
