### PR TITLE
Adds detection for Sprinklr crawler

### LINKED ISSUE #5953: New bots
- [x] Mozilla/5.0 (compatible; Embedly/0.2; +http://support.embed.ly/)
- [x] Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/55.0 BrandVerity/1.0 (http://www.brandverity.com/why-is-brandverity-visiting-me)
- [x] Apache-HttpClient/4.5.3-SNAPSHOT (Java/1.8.0_152)
- [ ] Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US) AppEngine-Google; (+http://code.google.com/appengine; appid: s~virustotalcloud)
- [x] curl/7.54.0
- [x] Sprinklr 2.0
- [x] PostmanRuntime/7.6.0
- [x] Wget/1.12 (linux-gnu)
- [x] python-requests/2.21.0
- [x] Lynx/2.8.6rel.4 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/0.9.8g

`Mozilla/5.0 (compatible; Embedly/0.2; +http://support.embed.ly/)` visit my sites every day more than 1000 times...

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #5953

### CODE REVIEW

**Review by sanchezzzhak — APPROVED** [review]

**Comment by sanchezzzhak** [comment]
I didn't find any mention of it being a bot.
It can also be an app that they release for their customers

**Comment by sgiehl** [comment]
didn't find something on there website. But this site lists it as bot: https://useragents.io/explore/browsers/types/bot-crawler/maker/sprinklr-inc-8e6/uas/sprinklr-2-0_4261e5f36611077b29da508766c7e22f

**Comment by sanchezzzhak** [comment]
I think this is a useragent from https://api-docs.sprinklr.com/
from webhooks

**Comment by sgiehl** [comment]
Nevertheless I think it's more a crawler, isn't it? 🤔

**Comment by sanchezzzhak** [comment]
according to most sources, this is most likely.

**Pull request merged**
