### PR TITLE
Introduce Yaml Lint check to prevent errors in yml files

### LINKED ISSUE #6433: Add a test using the Symfony yaml parser to parse all files
to avoid typos like #6432 in the future

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #6433

### CODE REVIEW

**Comment by sgiehl** [comment]
@Findus23 I've added a Linter instead of adding a test with symfony. Tried the problem we had before and it's correctly marked as error. See https://github.com/matomo-org/device-detector/pull/6434/commits/780b749e245e5989f8d33b88cf0e2b87ede266f9
Guess that should be enough to prevent further problems like this, right?

**Review by Findus23 — DISMISSED** [review]
This might even be better. Thanks for the change.

**Comment by Findus23** [comment]
Not sure how helpful error messages like this are:

```text
======================
= Linting YAML files =
======================
Error: syntax error: expected <block end>, but found '<block sequence start>' (syntax)
Error: Process completed with exit code 1.
```

**Comment by sanchezzzhak** [comment]
@sgiehl Is it possible to make a more detailed error reports in YAML Lint?

**Comment by Findus23** [comment]
Interestingly running `yamllint regexes/**/*.yml` locally gives nice error messages.

**Comment by sgiehl** [comment]
as @Findus23 mentioned. The errors should be highlighted in the diff on github. Guess there's not much that can be changed on the error messages. But imho that should be enough... we should at least now see if any yml file is broken

**Review by Findus23 — APPROVED** [review]
Sounds good to me

**Review by sanchezzzhak — APPROVED** [review]

**Pull request merged**
