### PR TITLE
Adding detection for several new browsers

### PR DESCRIPTION
**Pull request by sanchezzzhak**
pls merge

### CODE REVIEW

**Comment by sgiehl** [comment]
@Findus23  I'll gonna merge this soon. Maybe you could check if there are icons available for our icon repo

**Comment by Findus23** [comment]
@sgiehl , as the browsers are mostly from https://github.com/piwik/device-detector/issues/5609, there are high resolution icons for them available. I'll add them to Piwik-icons tomorrow.

**Comment by sanchezzzhak** [comment]
yes 
128x128 png
waterfox  -  https://udger.com/pub/img/ua/waterfox_big.png
epic  -  https://udger.com/pub/img/ua/epic_big.png
qutebrowser  -  https://udger.com/pub/img/ua/qutebrowser_big.png
dooble  -  https://udger.com/pub/img/ua/dooble_big.png
polarity -  https://udger.com/pub/img/ua/polarity_big.png
qupzilla  -  https://udger.com/pub/img/ua/qupzilla_big.png
coast   -   https://udger.com/pub/img/ua/coast_big.png
aloha browser -  https://udger.com/pub/img/ua/aloha_browser_big.png
iridium  -  https://udger.com/pub/img/ua/iridium_big.png

https://udger.com/resources/ua-list 
more browsers )

**Comment by Findus23** [comment]
@sanchezzzhak, I have added the icons for the new browsers: https://github.com/piwik/piwik-icons/commit/4665f499900986102cdf6617ab488fd1077d0fcc

Unfortuntly C1 and PT are affected by a bug I know for some time: I'll try to find a solution before the next piwik release: https://github.com/piwik/piwik-icons/issues/12

**Pull request merged**
