### PR TITLE
Update VoilaBot definition

### PR DESCRIPTION
**Pull request by shulard**
Orange build a new bot named OrangeBot : http://blog.lemoteur.fr/orangebot/

This bot replace VoilaBot which going to be removed very soon...

### CODE REVIEW

**Comment by sgiehl** [comment]
Thanks for the PR. Could you please update the tests, and maybe add a test for the new useragent

**Comment by shulard** [comment]
Of course :smile: it's ok now and I've added the new UA tests...

**Comment by shulard** [comment]
Are you ok with the last updates ?

**Comment by sgiehl** [comment]
Sorry for the delay. Changes are fine.

**Pull request merged**
