### PR TITLE
Adds detection for PlayStation 4 Pro console

### PR DESCRIPTION
**Pull request by liviuconcioiu**

### CODE REVIEW

**Comment by liviuconcioiu** [comment]
`  os:
    name: PlayStation
    short_name: PS3
    version: "4"
    platform: ""`
Here should be `4 Pro` but I don't know why it shows that.

**Comment by sgiehl** [comment]
@liviuconcioiu  that actually the operating system. Guess that doesn't differ between 4 and 4 Pro, does it?

**Comment by liviuconcioiu** [comment]
I've looked into the previous added consoles and I've seen their model added there. I just assumed that field should be `4 Pro`. On the other hand, PS4 runs on `Orbis OS`, and PS3 runs on `Cell OS`. Shouldn't those values be added as default, instead of the ones that are now?

**Comment by sgiehl** [comment]
@liviuconcioiu feel free to change the OS names detected for PlayStation if they are wrong...

**Pull request merged**
