### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by philippschulte**
### Description:

I am using a private fork of the rust version which is based on https://github.com/matomo-org/device-detector/releases/tag/6.2.1. The rust project runs every single test and the once listed in this PR are failing. I would highly appreciate if you would concider the changes of this PR for your next release candidate so that I don't have to continue fixing the tests when upgrading to the next version. Thanks in advance!

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by liviuconcioiu** [comment]
Hi @philippschulte. Tests are valid. Fire OS version is 7, because is based on Android 9. And the other test is an Android browser, that fakes the user-agent as iPad.

@mindreader can you look into this?

**Comment by sanchezzzhak** [comment]
client-hints not working for IOS/MACOS/IPADOS, Therefore, if they exist, then you should not trust that this is an Apple user agent.
http-x-xml-request header not send  for IOS/MACOS/IPAD OS this header is only sent by android from apps or browsers

so yes the tests are correct

**Comment by mindreader** [comment]
There are always code changes to be pulled into the rust version to bring it up to parity.

I did my best to structure the code similarly to make it easier to port the logic over, because there is no avoiding it.

I was intending to bring it up to parity soon, when I have some time.

**Comment by philippschulte** [comment]
Thanks everybody for confirming that the tests are correct! I'll compare the php and the rust code base and incorporate the necessary changes.

Is there a particular reason why you don't have a job which runs all the tests? It would be super helpful for people who maintain their own parser in other languages. Because I couldn't find such job in your CI I assumed that there is an issue with the tests.

Thanks for the great work you are doing here! I really appreciate it. Feel free to close this one.

**Comment by mindreader** [comment]
@philippschulte  I tagged a new updated version a few minutes ago.

As for your private fork, I understand the need to do hacky business things sometimes, but I would appreciate if you have made any performance enhancements that you consider contributing back. Maintaining and constantly updating from upstream is not really something you want to do all by yourself every few months as our code bases begin to diverge.

**Pull request closed without merging**
