### PR TITLE
Added recognition of ukr.net mail proxy and rambler mail image proxy

### PR DESCRIPTION
**Pull request by unisender-dev**
Added recognition of ukr.net mail proxy and rambler mail image proxy

### CODE REVIEW

**Comment by Findus23** [comment]
Hi, it would be great if you could add tests to the new bots (similar to https://github.com/matomo-org/device-detector/pull/5676/files)

**Comment by unisender-dev** [comment]
Hi, no problem. Will do my best.

**Comment by unisender-dev** [comment]
Hi, just curious, when you will tag new release and post it to packagist ? ;)

**Comment by sgiehl** [comment]
working on some other improvements at the moment. guess will release a new version afterwards

**Pull request merged**
