### PR TITLE
Add bots for Czech Republic

### PR DESCRIPTION
**Pull request by soukicz**
One major search engine and three "google shopping" alternatives.

### CODE REVIEW

**Comment by sgiehl** [comment]
Thanks for the PR. Would you mind adding some tests for those bots in [bots.yml](https://github.com/piwik/device-detector/blob/master/Tests/fixtures/bots.yml) or providing the user agents so we can add tests?

**Comment by Findus23** [comment]
Hi, It would be also nice if you could provide sqare icons for those websites, so I could add them to the piwik-icons.

**Comment by sgiehl** [comment]
@Findus23  are you including images for bots as well?

**Comment by Findus23** [comment]
Ah, thanks.
Forget what I wrote, I thought this was the searchengine-and-social-list
(@soukicz, you may want to add those websites [there](https://github.com/piwik/searchengine-and-social-list) if they are missing)

**Comment by soukicz** [comment]
Tests added

**Pull request merged**
