### PR TITLE
fix Intex regular group

### PR DESCRIPTION
**Pull request by sanchezzzhak**
Current regular correct for php but it wrong nodejs/javascript

### CODE REVIEW

**Comment by sgiehl** [comment]
nodejs/javascript doesn't support negative lookbehindes? If so the regex needs to be changed completely. Adding a `:` changes the result.

**Comment by sanchezzzhak** [comment]
yes, lookbehindes old different syntax
js `(^(?!filename)$)`
php `(?<!filename)`

test js/php
https://regex101.com/r/xT3xZ2/1

**Comment by sgiehl** [comment]
It also needs to match `Aqua Y2/V1 Linux/3.4.5 Android/4.2.2 Release/03.26.2013 Browser/AppleWebKit534.30 Mobile Safari/534.30 MBBMS/2.2;`

**Comment by sgiehl** [comment]
I'll close this one now. Feel free to reopen a pull request if you solved the problem.

**Pull request closed without merging**
